title: suakii
author: Jonghwa Park
email: suakii@gmail.com
description: >

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- tags.md

disqus:
  shortname: suakii

paginate: 5

markdown: kramdown

google_analytics: G-NFMQHCBNGG


exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
