title: suakii
author: Jonghwa Park
email: suakii@gmail.com
description: >

excerpt_separator: <!--more-->



plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- tags.md

disqus:
  shortname: suakii

paginate: 5

markdown: kramdown
highlighter: rouge

google_analytics: G-NFMQHCBNGG

url: https://suakii.github.io


exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
